# Generated by Django 5.0.2 on 2024-02-24 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_studentprofile_user_teacherprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="StudentProfile",
            new_name="PatientProfile",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.user",),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.user",),
        ),
        migrations.RenameField(
            model_name="patientprofile",
            old_name="student_id",
            new_name="patient_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
    ]
