# Generated by Django 5.0.2 on 2024-02-24 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_doctorprofile_rename_studentprofile_patientprofile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientprofile",
            old_name="patient_id",
            new_name="Patient_id",
        ),
    ]
