# Generated by Django 5.0.2 on 2024-02-25 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_doctorprofile_bio_doctorprofile_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientprofile",
            old_name="Patient_id",
            new_name="patient_id",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[("City1", "City1"), ("City2", "City2"), ("City3", "City3")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="government",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gov1", "Government1"),
                    ("Gov2", "Government2"),
                    ("Gov3", "Government3"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
