# Generated by Django 5.0.2 on 2024-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_doctorprofile_id_doctorprofile_profile_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="profile_id",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
